In [37]:
from sklearn.feature_extraction.text import CountVectorizer

In [38]:
data=[
    'one two three four five',
    'three four five six seven',
    ' five six eight nine nine',
    
]

In [39]:
cv= CountVectorizer()
x=cv.fit_transform(data)

In [40]:
cv.get_feature_names()

['eight', 'five', 'four', 'nine', 'one', 'seven', 'six', 'three', 'two']

In [41]:
x.toarray()

array([[0, 1, 1, 0, 1, 0, 0, 1, 1],
       [0, 1, 1, 0, 0, 1, 1, 1, 0],
       [1, 1, 0, 2, 0, 0, 1, 0, 0]], dtype=int64)

In [42]:
import pandas as pd

In [43]:
df=pd.read_csv('food.csv')
df

,name,ingredients,diet,prep_time,cook_time,flavor_profile,course,state,region
0,Balu shahi,"Maida flour, yogurt, oil, sugar",vegetarian,45,25,sweet,dessert,West Bengal,East
1,Boondi,"Gram flour, ghee, sugar",vegetarian,80,30,sweet,dessert,Rajasthan,West
2,Gajar ka halwa,"Carrots, milk, sugar, ghee, cashews, raisins",vegetarian,15,60,sweet,dessert,Punjab,North
3,Ghevar,"Flour, ghee, kewra, milk, clarified butter, su...",vegetarian,15,30,sweet,dessert,Rajasthan,West
4,Gulab jamun,"Milk powder, plain flour, baking powder, ghee,...",vegetarian,15,40,sweet,dessert,West Bengal,East
...,...,...,...,...,...,...,...,...,...
250,Til Pitha,"Glutinous rice, black sesame seeds, gur",vegetarian,5,30,sweet,dessert,Assam,North East
251,Bebinca,"Coconut milk, egg yolks, clarified butter, all...",vegetarian,20,60,sweet,dessert,Goa,West
252,Shufta,"Cottage cheese, dry dates, dried rose petals, ...",vegetarian,-1,-1,sweet,dessert,Jammu & Kashmir,North
253,Mawa Bati,"Milk powder, dry fruits, arrowroot powder, all...",vegetarian,20,45,sweet,dessert,Madhya Pradesh,Central
254,Pinaca,"Brown rice, fennel seeds, grated coconut, blac...",vegetarian,-1,-1,sweet,dessert,Goa,West

# Count vectorizer in Table

In [44]:
cv= CountVectorizer()
x=cv.fit_transform(df.ingredients)

In [45]:
cv.get_feature_names()

['acid',
 'all',
 'almond',
 'almonds',
 'aloo',
 'alum',
 'amaranth',
 'amchur',
 'and',
 'anise',
 'apricots',
 'arbi',
 'arhar',
 'arrowroot',
 'atta',
 'avocado',
 'axone',
 'baby',
 'badam',
 'bags',
 'baingan',
 'baking',
 'bamboo',
 'banana',
 'basmati',
 'bay',
 'bean',
 'beans',
 'beaten',
 'beef',
 'beetroot',
 'bell',
 'bengal',
 'besan',
 'bhaji',
 'bhatura',
 'bhuna',
 'biryani',
 'bitter',
 'black',
 'blend',
 'boiled',
 'bombay',
 'boondi',
 'bottle',
 'bread',
 'breasts',
 'brinjal',
 'brown',
 'buffalo',
 'butter',
 'cabbage',
 'canned',
 'capsicum',
 'cardamom',
 'carrot',
 'carrots',
 'cashew',
 'cashews',
 'cauliflower',
 'chana',
 'cheese',
 'chenna',
 'chhena',
 'chia',
 'chicken',
 'chickpea',
 'chickpeas',
 'chili',
 'chilies',
 'chilli',
 'chillies',
 'chole',
 'chopped',
 'chunks',
 'chutney',
 'cilantro',
 'cinnamon',
 'citric',
 'clarified',
 'coconut',
 'coloring',
 'condensed',
 'cooked',
 'coriander',
 'corn',
 'cottage',
 'cream',
 'crumbs',
 'cucumber',
 'curd',
 'curry',
 'daal',
 'dahi',
 'dal',
 'dates',
 'desiccated',
 'dharwadi',
 'dinner',
 'dough',
 'dried',
 'drumstick',
 'drumsticks',
 'dry',
 'duck',
 'edible',
 'egg',
 'eggplant',
 'eggs',
 'elachi',
 'elephant',
 'falooda',
 'fat',
 'fennel',
 'fenugreek',
 'fermented',
 'fillet',
 'fillets',
 'filling',
 'finger',
 'firm',
 'fish',
 'flakes',
 'flour',
 'flower',
 'flowers',
 'food',
 'foot',
 'forbidden',
 'french',
 'fresh',
 'fried',
 'frozen',
 'fruits',
 'fry',
 'garam',
 'garlic',
 'ghee',
 'ginger',
 'glutinous',
 'gobi',
 'gooseberry',
 'gourd',
 'gram',
 'grated',
 'gravy',
 'greek',
 'green',
 'greens',
 'gum',
 'gur',
 'heavy',
 'honey',
 'hot',
 'ice',
 'idli',
 'imli',
 'jaggery',
 'jeera',
 'jowar',
 'juice',
 'kala',
 'kasuri',
 'ke',
 'kewra',
 'khaman',
 'khoa',
 'khus',
 'kidney',
 'kitchen',
 'kokum',
 'ladies',
 'lamb',
 'leaf',
 'leaves',
 'lemon',
 'lentil',
 'lentils',
 'lime',
 'litre',
 'loaf',
 'lobster',
 'long',
 'low',
 'maida',
 'makki',
 'malai',
 'malvani',
 'mango',
 'marinade',
 'masala',
 'mashed',
 'masoor',
 'mawa',
 'meat',
 'melon',
 'methi',
 'milk',
 'millet',
 'mint',
 'mirch',
 'mixed',
 'molu',
 'moong',
 'mung',
 'mushroom',
 'mushrooms',
 'musk',
 'mustard',
 'mutton',
 'naan',
 'nestle',
 'nigella',
 'nuts',
 'oil',
 'olive',
 'onion',
 'onions',
 'orange',
 'palak',
 'panch',
 'paneer',
 'papaya',
 'papdi',
 'parboiled',
 'paste',
 'patte',
 'pav',
 'peanut',
 'peanuts',
 'pearl',
 'peas',
 'pepper',
 'peppers',
 'petals',
 'phoran',
 'pigeon',
 'pistachio',
 'plain',
 'pods',
 'poha',
 'pomegranate',
 'poppy',
 'pork',
 'potato',
 'potatoes',
 'potol',
 'powder',
 'powdered',
 'power',
 'prawns',
 'pudding',
 'pumpkin',
 'purpose',
 'raisins',
 'rapeseed',
 'rava',
 'raw',
 'red',
 'reduced',
 'refined',
 'rice',
 'ridge',
 'rind',
 'roasted',
 'rock',
 'roe',
 'rolls',
 'rose',
 'sabudana',
 'saffron',
 'salt',
 'sambar',
 'sattu',
 'sauce',
 'seed',
 'seeds',
 'semolina',
 'sesame',
 'sev',
 'sevai',
 'shimla',
 'shoot',
 'skimmed',
 'skinless',
 'sliced',
 'slices',
 'slivered',
 'soaked',
 'soda',
 'sooji',
 'sorghum',
 'soy',
 'spices',
 'spinach',
 'split',
 'star',
 'steamer',
 'stick',
 'sticky',
 'sugar',
 'sunflower',
 'surti',
 'sweet',
 'sweetened',
 'syrup',
 'tamarind',
 'tandoori',
 'tea',
 'thick',
 'thighs',
 'thin',
 'tindora',
 'tomato',
 'tomatoes',
 'toor',
 'turmeric',
 'urad',
 'valor',
 'vegetable',
 'vegetables',
 'vermicelli',
 'vinegar',
 'water',
 'watercress',
 'wheat',
 'whipping',
 'white',
 'whole',
 'wild',
 'wine',
 'yam',
 'yellow',
 'yoghurt',
 'yogurt',
 'yolks']

Array to DATAFRAMe

In [46]:
dfarray=pd.DataFrame(x.toarray())
dfarray

,0,1,2,3,4,5,6,7,8,9,...,326,327,328,329,330,331,332,333,334,335
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
251,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
252,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
253,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
254,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [59]:
df2=pd.merge(df,dfarray,right_index=True,left_index=True)
df2.tail()

,name,ingredients,diet,prep_time,cook_time,flavor_profile,course,state,region,0,...,326,327,328,329,330,331,332,333,334,335
250,Til Pitha,"Glutinous rice, black sesame seeds, gur",vegetarian,5,30,sweet,dessert,Assam,North East,0,...,0,0,0,0,0,0,0,0,0,0
251,Bebinca,"Coconut milk, egg yolks, clarified butter, all...",vegetarian,20,60,sweet,dessert,Goa,West,0,...,0,0,0,0,0,0,0,0,0,1
252,Shufta,"Cottage cheese, dry dates, dried rose petals, ...",vegetarian,-1,-1,sweet,dessert,Jammu & Kashmir,North,0,...,0,0,0,0,0,0,0,0,0,0
253,Mawa Bati,"Milk powder, dry fruits, arrowroot powder, all...",vegetarian,20,45,sweet,dessert,Madhya Pradesh,Central,0,...,0,0,0,0,0,0,0,0,0,0
254,Pinaca,"Brown rice, fennel seeds, grated coconut, blac...",vegetarian,-1,-1,sweet,dessert,Goa,West,0,...,0,0,0,0,0,0,0,0,0,0